- pytest_splunk_addon/standard_lib/app_test_generator.py
- pytest_splunk_addon/standard_lib/fields_tests/test_generator.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
There were 2 issue 
1. ACD-4138: The test generated were not ordered.
2. ACD-4136: The Field class was causing the issue in test scenarios.
ACD-4138
* The issue was resolved by sorting the test parameters 
ACD-4136
* By troubleshooting the issue, I checked that the error only occurs if the objects of Field class are provided to the test scenarios
* If the same information was provided in JSON format, the tests started working properly. 
* I'll update the detailed analysis in the ticket comment. 
Test execution with pytest-xdist plugin
> Acd 4136 pytest-xdist incompatibility issue fix

- .readthedocs.yml
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
- tests/test_splunk_addon.py
- Implemented Dynamic Index, Interval, and Retry support for the plugin.
- User can provide index name as **search-index** , interval as **search-interval** ,retry as **search-retry** in args
> ACD-4070:Added-dynamic-index-retry-support

- docs/field_tests.rst
- docs/how_to_use.rst
- Added documentation details for additional arguments in pytest-splunk-addon.
> ACD-4070:Added-doc-support

- pytest_splunk_addon/standard_lib/data_models/Change.json
As part of this JIRA, updated the Change.json DataModel "object_category" field with validation of accepting a single value in the event with no space.
For Example:
- The field can accept values like "registry_one", "win_eventlog".
- The field must not have values like "win eventlog", "res one".
> ACD-4278: validation of object_category field updated in Change data-model

- docs/field_tests.rst
Replaced "fields" with "knowledge objects" in field_tests section to increase the clarity of what is tested in the document
> ACD-4286: Changed field tests docs

- pytest_splunk_addon/standard_lib/cim_tests/field_test_helper.py
Replaced 'AND' condition to 'OR' condition in search query CIM test cases for clustered fields
> ACD-4305: Updated search query for cim test cases for clustered fields

- pytest_splunk_addon/standard_lib/cim_compliance/base_report.py
- pytest_splunk_addon/standard_lib/cim_compliance/ca_report_generator.py
- pytest_splunk_addon/standard_lib/cim_compliance/junit_parser.py
- pytest_splunk_addon/standard_lib/cim_compliance/markdown_report.py
Added 'add_section_description method' for the markdown_report module.
Added description for the tables generated in the report to make the report more intuitive.
> Acd 4285 Add Description in CIM compliance report

- pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
Changed packets field to be conditional fields, depending on the availability of the other fields present as part of ACD-3482 for the Network_traffc data model.
> Acd 4382 network traffic packets fields are not required

- pytest_splunk_addon/standard_lib/sample_generation/eventgen_parser.py
- pytest_splunk_addon/standard_lib/sample_generation/rule.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_generator.py
-   Added warning in console if replacementtype=all not supported for token rule.
i.e. `replacement_type=all is not supported for user rule applied to ##token_user_name## token.`
-  Added warning if a sample file is not found for a stanza in the eventgen.conf
i.e. `No sample file found for stanza : sample_file_two12.samples`
> Minor fixes for sample generation

- pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py
Change Summary:
- As per the configuration timestamp_type which is present in the conf file and can be either "plugin" or "event".
- For timestamp_type="plugin" we need to add epoch time in the params dict while ingesting events. along with the other info.
- This is updated in the class.
> Updated ingestor class for adding _time in event as per timestamp_type.

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
- pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
- pytest_splunk_addon/standard_lib/index_tests/test_generator.py
- pytest_splunk_addon/standard_lib/sample_generation/eventgen_parser.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_generator.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
As a part of this PR, following has been implemented:
Data ingestion is now done based on the conf file, i.e
- For the new conf file **'pytest-splunk-addon-data-generator.conf'** the number of events which will be ingested will depend on the no. of lines in sample file and the occurrence of  **'replacementType'= all**  in the conf file.
- **For eventgen.conf**, the number of events which will be ingested will depend on the count parameter. i.e 
For count = 0 or count > 250 or count parameter is not present in the conf, 250 events will be generated.
For count > 0 and count < 250 **'count'** no. of events will be ingested.
> Feature/ACD: 4496 data ingestion irrespective of test type

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/sample_generation/eventgen_parser.py
- pytest_splunk_addon/standard_lib/sample_generation/rule.py
- Raised appropriate exception when eventgen.conf and pytest-splunk-addon-data.conf are not found.
- Added 50 second sleep after ingestion for the data to become searchable.
- Handle named_tuple generation for TimeRule when replacement is %S.
> Base 10958 fixing issues

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
- pytest_splunk_addon/standard_lib/index_tests/test_templates.py
- Added ingestion fixtures to the test_templates to avoid setup_fixtures failures.
> BASE-10958:Reverted-setup_failures

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/event_ingestors/sc4s_event_ingestor.py
This PR contains:
- Updation of variable name for sc4s_host so as to be compatible with sc4s docker and external.
> BASE-7106:Changed-variable-names-for-sc4s-external

- pytest_splunk_addon/standard_lib/utilities/create_new_eventgen.py
This PR contains the fix for the bug in utility due to which it was not allowing to create the new pytest-splunk-addon-data.conf
The error is as shown below:
> BASE-11034: Resolution for the bug: 'KeyError: tokens' generated by the utility

- pytest_splunk_addon/standard_lib/sample_generation/eventgen_parser.py
- tests/addons/TA_fiction_indextime/default/pytest-splunk-addon-data.conf
- tests/addons/TA_fiction_indextime/samples/postfix_test_regex_two.samples
- tests/constants.py
- For SNOW addon the testcases were not properly generated due to similar stanza postfix.
- i.e snow_cmdb.samples &  all_snow_cmdb.samples
- Updated the plugin code to handle such scenarios and added a stanza in TA_fiction_indextime for testing.
> BASE-11061: Updated condition to avoid postfix stanza matching.

- pytest_splunk_addon/helmut_lib/SearchUtil.py
- pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- tests/test_splunk_addon.py
This PR contains:
- Updated list of input_type to ["file_monitor", "scripted_input", "default"] so as to avoid Encoding issue in other input_type.
-  Also, updated count in getFieldValueList function to return maximum of 4000 events.
-  Also, added clean_samples and clean_rules method for all the Github Actions tests so as to avoid usage of splunk with old events.
> Encode Event: Updated list of Input type to encode the events

- pytest_splunk_addon/splunk.py
When no containers are running and using xdist we must ensure two threads do not call any docker command at the same time as docker will attempt to create conflicting entries in the network
> [fix] Docker start race condition

- docs/index_time_tests.rst
Added FAQ section in index-time Doc
> ACD-4525: Added FAQ section in Doc

- pytest_splunk_addon/standard_lib/addon_parser/transforms_parser.py
- tests/addons/TA_fiction/default/props.conf
- tests/addons/TA_fiction/default/transforms.conf
Handle more complex syntax of regex to capture only valid named capture groups
> [fix] Handle situations where a TRANSFORMS REGEX uses _VAL

- pytest_splunk_addon/standard_lib/data_models/Change.json
- Changed the Change Datamodel to make action, object_attrs, object_category, object_id, and object_path fields required, and checking that the field is not a finite list and that the value is not empty,- space or contain quotes. 
- This fulfills the requirements for: https://jira.splunk.com/browse/BASE-6527 and https://jira.splunk.com/browse/BASE-6523
> Base 6523 updates to fields in change model

- docs/how_to_use.rst
- docs/index_time_tests.rst
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/app_test_generator.py
- pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- pytest_splunk_addon/standard_lib/index_tests/test_generator.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
- Updated the code to store the tokenised events for each stanza present in pytest-splunk-addon-data.conf, in the working directory.
- For each stanza present, a json file will be generated under the directory `.tokenized_events` with the events, key_fields and other related metadata
- Json files will be generated even if tests are not executed and --collect-only is used.
- To avoid generating these json files user can provide `--discard-eventlogs` param with the pytest command.
> Acd 4518 add tokenised events into log files

- pytest_splunk_addon/standard_lib/event_ingestors/hec_event_ingestor.py
- pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
ACD-4535
- Added support for ingesting data into custom indexes specified by the user within pytest-splunk-addon-data.conf files. 
- Added a warning message if a user tries to define index while using TCP/UDP/SC4S input type
> ACD-4535-Added support for custom indexes in pytest-splunk-addon-data.conf file

- docs/how_to_use.rst
- pytest_splunk_addon/splunk.py
* This PR contains the code for testing addons with an external forwarder host sending events to another Splunk deployment  where a user can search for received events.
* Four new pytest params are added to achieve the functionality
* Sample pytest command
pytest --splunk-type=external 
--splunk-app=<path-to-addon-package> 
--splunk-host=<hostname>                                    # Receiver Splunk instance where events are searchable.
--splunk-port=<splunk_management_port>                      # default 8089
--splunk-user=<username>                                    # default admin     
--splunk-password=<password>                                # default Chang3d!
--splunk-forwarder-host=<splunk_forwarder_host>             # Splunk instance where forwarding to receiver instance is …
> ACD-4543 Adds forwarder host params

- docs/how_to_use.rst
- pytest_splunk_addon/.ignore_splunk_internal_errors
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
- A new functionality is introduced in pytest-splunk-addon to suppress some unwanted errors in test_splunk_internal_errors.
- **Splunk related errors:** There is a file maintained in pytest-splunk-addon **.ignore_splunk_internal_errors** , user can add the string in the file and events cantaining these strings will be ignored by the search query.
- **Addon related errors:** To suppress these user can create a file with the list of strings and provide the file in the **--ignore-addon-errors** param while test execution.
- Each line in the file will be considered a separate string to be ignored in the events.
- Also updated the doc for the functionality
> INFRA-27682 Suppress internal errors

- pytest_splunk_addon/standard_lib/data_models/Change.json
Summary:
- Updating search constraint from **action="lockout" to result="lockout"** for Accounts_Lockout DataSet in Change DM.
- Jira Link: https://jira.splunk.com/browse/BASE-6614
> BASE-6614:Fixing-change-DM-search-constraint

- docs/requirements.txt
Adding missing sphinx_panels dependency within docs/requirements.txt file
> Adding sphinx_panels to pip requirements

- pytest_splunk_addon/standard_lib/addon_parser/props_parser.py
- tests/addons/TA_broken/default/props.conf
- tests/addons/TA_fiction/default/props.conf
- tests/addons/TA_fiction/lookups/ta_fiction_splund_component.csv
- tests/constants.py
fix(parser): Updated the field_parser regex for pytest-splunk-addon 
Updated the parser from [aA][sS]\s* to [aA][sS]\s+ to parse prefixes using as or AS correctly.
Also added new tests to verify the fixUpdated the field_parser regex for pytest-splunk-addon from _[aA][sS]\s*_ to _[aA][sS]\s+_ to parse prefixes using as or AS correctly.
> fix(parser): Updated the field_parser regex for pytest-splunk-addon

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- pytest_splunk_addon/standard_lib/event_ingestors/requirement_event_ingester.py
- tests/addons/TA_fiction/requirement_files/sample_requirement_file.log
Ingest requirement file events
- To enable requirement event ingestion use --requirement-test. 
- Sample requirement file is added to TA_fiction/requirement_file for testing.
- hec_raw_ingestor used to ingest raw requirement events to Splunk. 
- Requirement_event_ingester.py is added for parsing and extracting events from the log files. 
- Data is source typed using addons transforms.conf [Metadata: Sourcetype] for syslog sources.
Please review.
> Feat add/addon 32745

- tests/unit/conftest.py
- tests/unit/test_eventtype_parser.py
> eventtype_parser unit tests

- .gitignore
- pytest_splunk_addon/helmut_lib/SearchUtil.py
- pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
top 5 structurally unique events will be shown
>  feat: updating test output error message in case of failure for no_dash_not_empty tests

- .circleci/config.yml
- .github/workflows/test_matrix.yml
- .github/workflows/unit_tests.yml
- pytest_splunk_addon/standard_lib/sample_generation/sample_event.py
- tests/unit/tests_standard_lib/tests_sample_generation/test_rule.py
- tests/unit/tests_standard_lib/tests_sample_generation/test_sample_event.py
- part of:
INFRA-30041 (Not all tests delivered under this PR)
- Some cleanup in test jobs
> Feature/unit tests/infra 30041/sample generation

- .circleci/config.yml
- .github/workflows/test_matrix.yml
- Added 8.1 Splunk version in plugin's test matrix
> ci: updating matrix to execute tests on splunk 8.1

- pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
Minor update: If the model tag in the requirement file is of format Data_model:Dataset:sub_dataset. 
Requirement test will extract dataset and run the search with dataset.
> [model:Dataset] format support in requirement test

- pytest_splunk_addon/.ignore_splunk_internal_errors
Updated ignore_splunk_internal_error to suppress internal error failure.
Reference : https://jira.splunk.com/browse/INFRA-31687
> INFRA-31687: Updating expected internal errors to suppress internal error failure

- docker-compose-ci.yml
- docker-compose.yml
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/app_test_generator.py
- pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- pytest_splunk_addon/standard_lib/event_ingestors/requirement_event_ingester.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
- tests/requirement_test/sample_requirement.log
- tests/requirement_test/sample_requirement_failure.log
- tests/test_splunk_addon.py
- tests/unit/tests_standard_lib/test_app_test_generator.py
- tests/unit/tests_standard_lib/test_event_ingestors/test_ingestor_helper.py
- tests/unit/tests_standard_lib/test_event_ingestors/test_requirement_event_ingestor.py
- tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py
Feature add:
- Requirement test event ingestion is done via SC4S.
- As logs are ingested via SC4S “extract_regex_transforms()” “extract_sourcetype()” functions are no longer needed to determine source type of event using transforms.conf
-  In the previous version the complete event was searched for via Splunk search but as now we use SC4S, the event ingested is processed and does not contain HEADER. Syslog Header is removed  from search by function strip_syslog_header()
- Change location of input requirement files from package/requirement_files -> tests/requirement_tests/  as package folder gets released and it cannot contain logs.
- Location of files and whether to run the requirement test or not will be given by the “requirement-test” parameter in pytest.ini file …
> feat: Req_test for syslog sources with event ingestion via SC4S

- poetry.lock
- pyproject.toml
- tests/unit/tests_standard_lib/test_event_ingestors/conftest.py
- tests/unit/tests_standard_lib/test_event_ingestors/test_requirement_event_ingestor.py
resolution for issue https://github.com/splunk/pytest-splunk-addon/issues/367
recordtype is only used in unit tests so we can easily remove it
> remove recordtype library

- docs/how_to_use.rst
- docs/requirements.txt
- poetry.lock
- pyproject.toml
- pytest_splunk_addon/plugin.py
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
- Added pytest params
> --event-file-path
Path to tokenized events file
> --tokenized-event-source
Source of tokenized events(Generate new events or use pregenerated events)
> --ingest-events
Should ingest events or not (True|False)
> --execute-test
Should execute test or not (True|False)
- Downgraded junitparser version to 1.6.3 to fix `cim-report` feature
- Added Sphinx package in requirements to fix `test_docstrings` test of pytest-splunk-addon
> Added options to separate event generation, event ingestion and test execution stage

- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
data model error message was showing the list_unmatched_datamodel_splunkside, list_unmatched_datamodel_requirement_file in place of  extracted TA values, given models in requirement file.
Error shows correct values now -
```
AssertionError: data model check: False 
E         data model in requirement file  ['Change']
E          data model extracted by TA ['Change_Endpoint_Changes']
E         sourcetype of ingested event: xmlwineventlog 
E         
E       assert False
```
> fix: data model mismatch error message

- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
- tests/requirement_test_modinput/sample_requirement_test_modinput.log
Fix: JVM Ingestion failure where source contains "=" sign. If we add double qoutes around search string for host source sourcetype it resolves the issue.
Added a sample source with "=" sign to the test.
> fix: Ingestion failure where special char in host,source and sourcetype

- .releaserc
* The semantic-release stage was breaking due to the regex of .releaserc, which was making 2 versions from pyproject.toml. So, updated regex to match adequate version.
> ci: updated .releaserc to resolve release issue

- pyproject.toml
- pytest_splunk_addon/__init__.py
This commit rollbacks the version update pushed by semantic-release-bot and should trigger a new release procedure, so we can actually release a new version of the PSA (both in Github and PyPi).
> chore: rollback version bump

- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
Please review
Changed the field messaging format to display errors as -
```
Field extraction errors: {
E             "Key value in requirement file: action": "create",
E             "Key value extracted by Splunk: action": "created",
E             "Key value in requirement file: change_type": "filesyste",
E             "Key value extracted by Splunk: change_type": "filesystem"
E         }
```
> fix: field extraction error message

- pytest_splunk_addon/standard_lib/event_ingestors/requirement_event_ingester.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py
- tests/constants.py
- tests/requirement_test_scripted/sample_requirement_test_scripted.log
- tests/requirement_test_scripted/sample_requirement_test_scripted_failure.log
- tests/requirement_test_uf/sample_requirement_test_uf_failure.log
- tests/test_splunk_addon.py
Please review following changes - 
- Transport type- scripted input support added for requirement test
- Addon used for UF transport type is also utilized to test scripted input.
- Added test_splunk_app_requirements_scripted for scripted input type
- Uses HecRawEventIngestor class to ingest data
> feat: Scripted input support requirement test

- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
Please review -
Removed function use to replace the key prefix before matching
> fix: duplicate key issue mscs

- poetry.lock
- pyproject.toml
poetry-dynamic-versioning is not used in the CI anymore, so removing this dev dependency.
> chore: remove poetry-dynamic-versioning

- .github/workflows/build-test-release.yml
Inspired by https://github.com/pypa/pip/commit/fa2d428e436c26dc072744aadd4d5d58ea42b743
Docs: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
> ci: apply concurrency for build-test-release job

- pytest_splunk_addon/standard_lib/addon_requirements_basic.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
- tests/constants.py
- tests/test_splunk_addon.py
Changes in the PR-
1. Separate addon_basic class for requirement test,  keeping the same test functionality we currently have.
2. Add splunk_ingest_data fixture to test_requirement_params arguments
2. For this change we will need to update requirement_test/test_addon.py to - 
```
from pytest_splunk_addon.standard_lib.addon_requirements_basic import RequirementBasic
class Test_App(RequirementBasic):
def empty_method():
pass
```
> feat!: Refactor Basic class for requirement test 

- .github/workflows/build-test-release.yml
From `poetry` [README](https://github.com/python-poetry/poetry#installation):
Warning: The previous get-poetry.py installer is now deprecated, if you are currently using it you should migrate to the new, supported, install-poetry.py installer.
And some minor changes.
> ci: multiple changes to the pipeline

- .github/workflows/build-test-release.yml
While we are migrating to Kubernetes, I think it will be still valuable to remove bug in a pipeline not to waste Github's resources for no reason and maybe speed up our pipeline.
> ci: remove matrix option from test-splunk-matrix step

- pytest_splunk_addon/standard_lib/addon_requirements_basic.py
- tests/constants.py
There is no need to run test_events_with_untokenised_values test when running
requirement tests. It is needed when running knowledge tests.
> refactor: remove test_events_with_untokenised_values from RequirementBasic

- .github/workflows/build-test-release.yml
This PR runs tests based on `-k` parameter in the CI, so instead of waiting > 1 hour until tests are finished, now it is 30 minutes of waiting :)
This PR also removes `snyk` and reorganises the overall pipeline to execute things faster.
> ci: make tests run in parallel

- poetry.lock
- pyproject.toml
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/event_ingestors/file_monitor_ingestor.py
- pytest_splunk_addon/standard_lib/event_ingestors/hec_event_ingestor.py
- pytest_splunk_addon/standard_lib/event_ingestors/hec_metric_ingestor.py
- pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py
- pytest_splunk_addon/standard_lib/event_ingestors/requirement_event_ingester.py
- pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py
This PR fixes the `semgrep` failures.
> chore: fix semgrep issues

- pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py
- tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py
Handle checkpoint CEF log.
CEF format sample- 
```
Jan 11 10:25:39 host CEF:Version|Device Vendor|Device Product|Device Version|Device Event Class ID|Name|Severity|[Extension]
```
Checkpoint format sample-
```
time=1611840576|hostname=r81-t279-leui-main-take-2|severity=Critical|confidence_level=High|product=Anti Malware New Anti Virus|action=Detect|ifdir=inbound|loguid= .....
```
In the case of Checkpoint CEF is missing the header. Hence generic CEF regex does not work for checkpoint logs.
Have not added a test- as checkpoint TA is not present and the test will fail as DM mapping and field level tests won't work
> fix: checkpoint cef format issue

- .github/CODEOWNERS
As requested, adding SME team to be asked to review changes related to `pytest_splunk_addon/standard_lib/data_models` folder.
> chore: SMEs now own data_models

- pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
In the MSCS TA, Input source type i.e  mscs:azure:event hub  but after transforming the event source type will be azure:monitor:aad, azure:eventhub:cosmosdb. These transformation cause ingestion failure in requirement test.
Many other TA's are affected too. Hence remove source type from search
https://splunk.atlassian.net/browse/ADDON-50593
> fix: sourcetype mismatch between ingested vs requirement file

- docker-compose-ci.yml
- docker-compose.yml
SC4S publishes the latest images on Github now than docker hub
Updating path for pytest splunk addon
Updated in addon template too https://github.com/splunk/addonfactory-repository-template/pull/252
> fix: SC4S latest container location

- .github/workflows/build-test-release.yml
- .licenserc.yaml
- poetry.lock
- pyproject.toml
- pytest_splunk_addon/plugin.py
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/app_test_generator.py
- pytest_splunk_addon/standard_lib/cim_tests/test_generator.py
- pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
- pytest_splunk_addon/standard_lib/fields_tests/test_generator.py
- pytest_splunk_addon/standard_lib/index_tests/test_generator.py
- pytest_splunk_addon/standard_lib/sample_generation/pytest_splunk_addon_data_parser.py
- pytest_splunk_addon/standard_lib/sample_generation/schema.xsd
- tests/e2e/constants.py
- tests/e2e/test_splunk_addon.py
PR created to include requirement unit test into PSA (for now stored in [splunk/addonfactory-workflow-requirement-files-unit-test](https://github.com/splunk/addonfactory-workflow-requirement-files-unit-tests) In general, There are two checks added:
- one of the recommended fields implemented previously [here](https://github.com/splunk/addonfactory-workflow-requirement-files-unit-tests/blob/main/test_lib/test_cim.py) - now it is a new cim test. New fixture was added - `splunk_dm_recommended_fields` to get datamodel definition. The new approach was used here instead of a static definition API call to Splunk instance is performed. It requires CIM Add-on to be installed in the Splunk test environment, but it was already added previously.
- schema validation from …
> feat: replacing req unit tests

- pyproject.toml
- pytest_splunk_addon/standard_lib/utilities/sample_splitter.py
install script
fix for spitters contain '/'
> chore: sample splitter script

- pytest_splunk_addon/standard_lib/addon_basic.py
A search query for test_events_with_untokenised_values is updated so token name could have only alphanumerical characters with 2 special characters hyphen and an underscore. 
Ref: https://splunk.atlassian.net/browse/AQA-76
> fix: Updated search query for untokenized events test case

- pytest_splunk_addon/standard_lib/utilities/xml_event_parser.py
- tests/unit/tests_standard_lib/test_utilities/test_xml_event_parser.py
issue caused by incorrect handling of syslog header, removed "-" from rfc5424 + refactoring
previously it was:
`(?:(\d{4}[-]\d{2}[-]\d{2}[T]\d{2}[:]\d{2}[:]\d{2}(?:\.\d{1,6})?(?:[+-]\d{2}[:]\d{2}|Z)?)|-)\s(?:([\w][\w\d\.@-]*)|-)\s(.*)$`
now it is:
`(?:(\d{4}[-]\d{2}[-]\d{2}[T]\d{2}[:]\d{2}[:]\d{2}(?:\.\d{1,6})?(?:[+-]\d{2}[:]\d{2}|Z)?))\s(?:([\w][\w\d\.@-]*)|-)\s(.*)$`
it's hot fix, in long term we should have more universal solution
> fix: handling '-' in the event

- poetry.lock
- pyproject.toml
PSA sometimes throws an error "Temporary failure in name resolution" which makes some tests to fail which results in a retry which takes time and is not reliable.
The specific log can be found here: https://github.com/splunk/splunk-add-on-for-cisco-asa/actions/runs/4627279372/job/12563451275
PSA uses splunksplwrapper (helmut) to make requests to Splunk itself, so the fix for this problem is to improve that library. The merged fix can be found [here](https://github.com/splunk/splunksplwrapper/pull/55). It makes splunksplwrapper to retry failed requests up to 3 times with 5 seconds delay. This should increase the reliability of the tests.
> fix: update splunksplwrapper dep where it retries service init

- poetry.lock
- pyproject.toml
New version of splunksplwrapper deals with a deprecation warning regarding using ResultsReader from splunk-sdk.
> feat: bump splunksplwrapper to 1.1.1

- .github/workflows/build-test-release.yml
- .gitignore
- pytest_splunk_addon/plugin.py
- pytest_splunk_addon/splunk.py
- tests/e2e/incorrect_hec_token_conftest.py
- tests/e2e/test_splunk_addon.py
Changes:
- deprecate default value of splunk-hec-token - give a warning when it's used
- add console handler to logger - warnings and errors beside being logged to pytest_splunk_addon.log are also logged to console
- other minor refactors from PR-803
Already released on develop and tested on couple of repos.
https://github.com/splunk/splunk-add-on-for-google-workspace/pull/515
References:
https://splunk.atlassian.net/browse/ADDON-66599
https://github.com/splunk/pytest-splunk-addon/pull/803/files
---------
> fix: ADDON-66599 deprecate splunk-hec-token default value and break test execution on exception

- poetry.lock
- pyproject.toml
This PR makes it so PSA accepts any version of `addonfactory-splunk-conf-parser-lib` (Splunk-owned library).
> fix: accept any version of addonfactory-splunk-conf-parser-lib

- poetry.lock
- pyproject.toml
PR introduces temporary solution of potential FP testaces caused by change of workers initiation between pytest-xdist v2 and v3. 
https://splunk.atlassian.net/browse/ADDON-67242
> fix: pytest-xdist version limitation

- poetry.lock
- pyproject.toml
PR takes back the limitation imposed on pytest-xdist version. There are no false positive tests results. The behaviour is expected. 
[ADDON-67668](https://splunk.atlassian.net/browse/ADDON-67668)
> fix: update of pytest-xdist version

- .github/workflows/build-test-release.yml
- .licenserc.yaml
- Dockerfile.splunk
- entrypoint.sh
- poetry.lock
- pyproject.toml
- pytest_splunk_addon/docker_class.py
- pytest_splunk_addon/splunk.py
- tests/e2e/test_splunk_addon.py
This PR contains following changes
- Added code for lovely-pytest-docker in PSA and  migrated to v2 version of docker-compose as GitHub runners have stopped supporting docker compose v1.
- Also fixed the CI runs for e2e tests as it always running on latest splunk instead of version provided by addonfactory-splunk-matrix.
> refactor: adding lovely-pytest-docker code

- .github/workflows/build-test-release.yml
- pytest_splunk_addon/splunk.py
- tests/e2e/test_splunk_addon.py
There was a bug in PSA where if in splunk_ingest_data first worker errors out or throws exception then it does not write to a file, now other workers would be waiting indefinitely for the file to be present, So the execution would continue in infinitly.
To handle this scenario, we can handle the exception thrown by the first worker and make sure that in any case it writes to a file, so that other workers don't wait indefinitly
> fix: handling infinite loop

- Dockerfile.tests
- docs/cim_compliance.md
- docs/cim_tests.md
- docs/field_tests.md
- docs/generate_conf.md
- docs/how_to_use.md
- docs/index_time_tests.md
- docs/sample_generator.md
- Updated the md files for proper reference.
- Added missing brackets
Fixes #834
> docs: fixing documentation

- .releaserc
Similar as in https://github.com/splunk/addonfactory-solutions-library-python/blob/c14f9909ce1228a2896a81689dc58989eb9d341c/.releaserc#L31C1-L32C60.
> ci(release): allow beta versions for pyproject.toml file

- pytest_splunk_addon/standard_lib/data_models/Network_Resolution.json
Updated 2  fields in Network Resolution model.
- Added expected values for reply_code_id which has corresponding reply_code.
- Added expected values for reply_code.
> feat: updating network resolution model

- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/standard_lib/addon_parser/props_parser.py
- pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
- pytest_splunk_addon/standard_lib/utils.py
When tests are ran with multiple workers, duplicate logging is observed because every workers logs the warning.
This PR fixes that.
> fix: do not log .conf parser warnings from all workers

- pytest_splunk_addon/splunk.py
This commit removes unused properties for tests which passed.
This PR substitutes #873 PR.
> fix: trim test report

- docs/how_to_use.md
- docs/index.md
- docs/requirement_tests.md
- docs/sample_generator.md
- mkdocs.yml
This PR updates the doc for how_to_use section and add the documentation for requirement tests.
ref: https://splunk.atlassian.net/browse/ADDON-73384
> docs: Userguide enhancements

- docs/api_reference/cim_compliance_report.md
- mkdocs.yml
- pytest_splunk_addon/addon_parser/fields.py
- pytest_splunk_addon/addon_parser/props_parser.py
- pytest_splunk_addon/cim_compliance/cim_report_generator.py
- pytest_splunk_addon/cim_compliance/markdown_report.py
- pytest_splunk_addon/cim_compliance/markdown_table.py
- pytest_splunk_addon/cim_compliance/plugin.py
- pytest_splunk_addon/cim_tests/data_model.py
- pytest_splunk_addon/cim_tests/data_model_handler.py
- pytest_splunk_addon/cim_tests/data_set.py
- pytest_splunk_addon/cim_tests/test_generator.py
- pytest_splunk_addon/cim_tests/test_templates.py
- pytest_splunk_addon/event_ingestors/hec_metric_ingestor.py
- pytest_splunk_addon/event_ingestors/hec_raw_ingestor.py
- pytest_splunk_addon/event_ingestors/ingestor_helper.py
- pytest_splunk_addon/fields_tests/sample_parser.py
- pytest_splunk_addon/fields_tests/test_generator.py
- pytest_splunk_addon/fields_tests/test_templates.py
- pytest_splunk_addon/index_tests/test_generator.py
- pytest_splunk_addon/index_tests/test_templates.py
- pytest_splunk_addon/sample_generation/pytest_splunk_addon_data_parser.py
- pytest_splunk_addon/sample_generation/rule.py
- pytest_splunk_addon/sample_generation/sample_event.py
- pytest_splunk_addon/sample_generation/sample_generator.py
- pytest_splunk_addon/sample_generation/sample_xdist_generator.py
- pytest_splunk_addon/sample_generation/time_parser.py
- pytest_splunk_addon/splunk.py
- pytest_splunk_addon/tools/cim_field_report.py
This PR updates API reference documentation as below
-  add missing function implementation and its params.
-  correcting parameters doc for some functions
-  add documentation for cim-compliance-report
Ref: https://splunk.atlassian.net/browse/ADDON-75003
> docs: update api reference documentation

- .github/workflows/build-test-release.yml
This PR sets ubuntu version to 22.04 for scripts run with python 3.7.
Reference: [ADDON-75861](https://splunk.atlassian.net/browse/ADDON-75861)
> ci: fix ubuntu version to 22.04

- pytest_splunk_addon/data_models/Authentication.json
- pytest_splunk_addon/data_models/Intrusion_Detection.json
- pytest_splunk_addon/data_models/Network_Traffic.json
- pytest_splunk_addon/data_models/Performance.json
Added changes based on CIM 6.0.0 and CIM 5.3.2 changes
Added Session ID in Authentication Model: https://cd.splunkdev.com/EnterpriseSecurity/sa-commoninformationmodel/-/merge_requests/545
Signature field description change in Intrusion Detection Model: https://cd.splunkdev.com/EnterpriseSecurity/sa-commoninformationmodel/-/merge_requests/542
Protocol Version description change in Network Traffic Model: https://cd.splunkdev.com/EnterpriseSecurity/sa-commoninformationmodel/-/merge_requests/544
Power field description change in Performance Model: https://cd.splunkdev.com/EnterpriseSecurity/sa-commoninformationmodel/-/merge_requests/543
> feat: Upgrade CIM to 6.0.0

- .github/workflows/build-test-release.yml
Downgrading Ubuntu version as python 3.7 is no longer supported on latest
> chore: downgrade ubuntu version

- .github/workflows/build-test-release.yml
- pytest_splunk_addon/CIM_Models/datamodel_definition.py
- pytest_splunk_addon/data_models/Change.json
- tests/e2e/addons/TA_cim_addon/default/eventtypes.conf
- tests/e2e/addons/TA_cim_addon/default/props.conf
- tests/e2e/addons/TA_cim_addon/default/pytest-splunk-addon-data.conf
- tests/e2e/addons/TA_cim_addon/default/tags.conf
- tests/e2e/addons/TA_cim_addon/samples/test_change.xml
- tests/e2e/constants.py
- tests/e2e/test_splunk_addon.py
This PR updates the condition for the object_category field of the Change DataModel.
Added e2e tests to cover this check.
> fix: update field validation condition

- pytest_splunk_addon/addon_parser/transforms_parser.py
- tests/e2e/addons/TA_broken/default/props.conf
- tests/unit/tests_standard_lib/test_addon_parser/test_transforms_parser.py
props.conf had invalid syntax using line breakers (issue reported here: https://splunk.atlassian.net/browse/ADDON-72549 
). The incorrect format is causing warnings in the splunkd log, which could be easily prevented by correcting the props conf file like in this [example](https://github.com/splunk/splunk-add-on-for-microsoft-cloud-services/pull/1196/files).
Related Jira:
https://splunk.atlassian.net/browse/ADDON-77954
Example local run:
> fix: terminate tests for improper props conf

- .github/workflows/build-test-release.yml
- pytest_splunk_addon/addon_parser/transforms_parser.py
- tests/e2e/addons/TA_broken/default/props.conf
- tests/unit/tests_standard_lib/test_addon_parser/test_transforms_parser.py
Reverts splunk/pytest-splunk-addon#901
We decided to keep the check for conf files in app inspect (the check is already implemented, but requires a fix) : https://splunk.atlassian.net/browse/A3-1577
Also upgraded pip for test-splunk-external job: https://github.com/splunk/pytest-splunk-addon/actions/runs/13541590970/job/37843909257#step:3:19
> Revert "fix: terminate tests for improper props conf"

- pytest_splunk_addon/event_ingestors/hec_event_ingestor.py
- tests/unit/tests_standard_lib/test_event_ingestors/conftest.py
improve hec batch to be not a JSON array to conform specification: https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Example_3:_Batched_data (ADDON-79329)
> fix: improve hec batch to be not a JSON array to conform specification

- .github/workflows/build-test-release.yml
- docker-compose.yml
- pytest_splunk_addon/docker_class.py
- pytest_splunk_addon/splunk.py
- Update the matrix version to get the latest splunk version to be used in e2e tests
- Fixes the issue with the e2e tests execution where the tests were failing due to issues in the docker services being created.
> ci: fix docker env creation for e2e tests

- pytest_splunk_addon/data_models/Endpoint.json
Fixes the issue with validation condition being used while executing SPL query to search events for particular testcase.
Reference issue: https://github.com/splunk/splunk-add-on-for-unix-and-linux/runs/49911799683
Test run: https://github.com/splunk/splunk-add-on-for-unix-and-linux/actions/runs/17581963680
> fix: field validation condition
