docker-compose-ci.yml, pytest_splunk_addon/splunk.py, tests/docker-compose.yml
For use with index time testing this change will expose the hec port and provide an env for password
=> Expose HEC and S2S for future use

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
Resolve minor Network traffic json file issue
=> Acd 4166 minor cim issue for Network traffic json

pytest_splunk_addon/splunk.py, tests/addons/TA_SavedSearch/default/app.conf, tests/addons/TA_SavedSearch/default/props.conf, tests/addons/TA_SavedSearch/default/savedsearches.conf, tests/addons/TA_SavedSearch/default/transforms.conf, tests/addons/TA_SavedSearch/lookups/ta_saved_search_lookup.csv, tests/addons/TA_SavedSearch/metadata/default.meta, tests/enable_saved_search_conftest.py, tests/test_splunk_addon.py
- Added setup fixture `splunk_setup`. 
- Added a plugin test to test the functionality of the fixture.
=> Acd 4179 support setup fixtures

pytest_splunk_addon/standard_lib/fields_tests/test_templates.py, tests/test_splunk_addon.py
Concat the stats command with field queries for quicker execution.
=> feature/acd-4215: Concat the stats command with field query

.readthedocs.yml
=> Feature/acd 4209 fix readthedocs.yml file

pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
Added support for Dynamic-interval and retry for CIM Tests as a part of ACD-4070 JIRA.
=> ACD-4070:Updated-retry-interval-cim-tests

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
Updated the expected values for the protocol field in network traffic datamodel
=> acd-4277: Updated the expected values for protocol field in network network traffic datamodel

pytest_splunk_addon/standard_lib/cim_tests/test_generator.py, pytest_splunk_addon/standard_lib/cim_tests/test_templates.py, tests/addons/TA_CIM_Broken/default/eventtypes.conf, tests/addons/TA_CIM_Broken/default/tags.conf, tests/constants.py
- Created the fixture to get add-on associated all eventtype list
- Updated the eventtype mapped datamodel query by using the list of eventtype and datamodels tag.
- Verified the updated test case on multiple add-on.
=> ACD-4213: Updated the eventtype mapped CIM data model test case

docs/cim_compliance.rst, docs/how_to_use.rst, docs/index.rst, docs/overview.rst
* Created a page for CIM Compliance report and added details.
=> ACD-4289: Documentation for CIM Report

pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
Resolved issue of Merge Conflict for record-property.
=> ACD-3806:Updated-the-record-property

pytest_splunk_addon/standard_lib/data_models/Web.json
Changed uri_path to an optional field, and added a validity check for the field.
=> Acd 4380 web dm uri path

pytest_splunk_addon/standard_lib/data_models/Web.json
changed the url_length field to an optional field.
=> Acd 4381 web datamodel url length

pytest_splunk_addon/standard_lib/data_models/Web.json
Changed the app field to an optional field
=> ACD-4379-web-model-app-field-is-optional

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json, pytest_splunk_addon/standard_lib/data_models/Web.json
Changed the fields from optional to conditional fields so that their validity would still be checked, and made some improvements for checking some field validity.
=> Making some improvement changes

pytest_splunk_addon/standard_lib/sample_generation/sample_event.py
- Removed the for loop and use next function to get token from the match list
=> Removed the for loop and use next function to get token from match list

pytest_splunk_addon/standard_lib/utilities/create_new_eventgen.py, pytest_splunk_addon/standard_lib/utilities/mapping.py, setup.py
Added files:
1. create_new_eventgen.py: contains logic for converting the existing eventgen.conf into a new conf file required for index-time testing
2. mapping.py: Helper file which contains required mappings.
=> ACD-4340: Added utility for generating new eventgen.conf

pytest_splunk_addon/standard_lib/sample_generation/rule.py, pytest_splunk_addon/standard_lib/sample_generation/sample_event.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py, pytest_splunk_addon/standard_lib/utilities/create_new_eventgen.py, pytest_splunk_addon/standard_lib/utilities/mapping.py, setup.py
- Added user warnings while error in ingestions.
- Updated code for grp regex replacement.
- Added warning if unidentified input_type is obtained from conf file.
=> Replace tokens for matched grps in regex

pytest_splunk_addon/standard_lib/index_tests/test_generator.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
As a part of this PR:
- Added Max count param=250 if the count is too large.
=> Added-support-of-maxcount

pytest_splunk_addon/standard_lib/sample_generation/rule.py, pytest_splunk_addon/standard_lib/sample_generation/sample_event.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
- Updated IP range in url rule to 192.168.0.0
- Handled Empty lines in sample files.
=> Url ip range and empty lines in sample file

pytest_splunk_addon/standard_lib/data_models/Intrusion_Detection.json
Changed the field for user in the IDS data model to optional as per request.
=> Initial commit, changing user field to optional

tests/addons/TA_fiction_indextime/default/props.conf, tests/addons/TA_fiction_indextime/default/pytest-splunk-addon-data-generator.conf, tests/addons/TA_fiction_indextime/default/transforms.conf, tests/addons/TA_fiction_indextime/samples/file_monitor_time_stamp_plugin.samples, tests/addons/TA_fiction_indextime/samples/modinput_host_event_time_plugin.samples, tests/addons/TA_fiction_indextime/samples/scripted_input_key_fields_fiction.samples, tests/addons/TA_fiction_indextime/samples/scripted_input_line_breaking_fiction.samples
Added a few more positive scenarios for the functional testing of Plugin.
=> ACD-4498 Added more fiction tests

pytest_splunk_addon/splunk.py, pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py, pytest_splunk_addon/standard_lib/index_tests/test_generator.py, pytest_splunk_addon/standard_lib/sample_generation/__init__.py, pytest_splunk_addon/standard_lib/sample_generation/sample_event.py, pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
=> ACD-4483: Added support for xdist

pytest_splunk_addon/standard_lib/event_ingestors/hec_event_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/hec_metric_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/sc4s_event_ingestor.py
Raise exception if invalid token: Fixed
=> ACD-4483: Raise exception if invalid token: Fixed

pytest_splunk_addon/standard_lib/sample_generation/rule.py
As a part of this PR, following change has been made:
Minor change in rule.py to solve the issue in Juniper due to which data was not generated properly.
=> BASE-10966: Updated rule.py to fix juniper failure

docs/api_reference/api_reference.rst, docs/api_reference/index_time_tests.rst, docs/index_time_tests.rst, docs/overview.rst, docs/sample_generator.rst, pytest_splunk_addon/standard_lib/__init__.py, pytest_splunk_addon/standard_lib/addon_basic.py, pytest_splunk_addon/standard_lib/index_tests/__init__.py, pytest_splunk_addon/standard_lib/index_tests/test_generator.py, pytest_splunk_addon/standard_lib/index_tests/test_templates.py
This PR contains final updates made to the docs for v1.3.0
=> BASE-10967: Updated docs for v1.3.0

docs/generate_conf.rst, docs/index_time_tests.rst, docs/sample_generator.rst, pytest_splunk_addon/standard_lib/index_tests/test_generator.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py, pytest_splunk_addon/standard_lib/utilities/create_new_eventgen.py, tests/addons/TA_fiction_indextime/default/pytest-splunk-addon-data.conf, tests/addons/TA_fiction_indextime_broken/default/pytest-splunk-addon-data.conf
Calculate expected eventcount dynamically
=> BASE-10963: Calculate expected eventcount dynamically

pytest_splunk_addon/standard_lib/sample_generation/sample_event.py, pytest_splunk_addon/standard_lib/sample_generation/sample_generator.py
Worked on review comments on PR 134
=> resolved review comments

pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
This PR contains:
- Resolved UnicodeEncode Error while Reading the sample file by using encoding="utf-8".
- Faced the issue while testing Windows TA and sample files were **server2k8.WindowsUpdateLog** and **Security.windows2016**
=> BASE-11060-Resolved-UnicodeEncode-Error

pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py
- This PR contains: fix for Encoding Error occurred due to characters like {...} were there in samples of CiscoESA Addon.
=> Fix-for-Encoding-issue-in-esa

pytest_splunk_addon/standard_lib/sample_generation/rule.py
-  Added the URL path support in URL rule
=> Updated the URL rule to add url path configuration

docs/how_to_use.rst, docs/index_time_tests.rst, docs/sample_generator.rst
As a part of this PR, the following has been updated:
- Added details about the **breaker** parameter in **Data Generator** Section.
- Updated **How To Use** section.
- Updated **Index Time Tests** Section.
=> Updated Documentation for pytest-splunk-addon v130 

pytest_splunk_addon/splunk.py, pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py
Reverts splunk/pytest-splunk-addon#157
=> Revert "[fix] Change generation lock to single file"

pytest_splunk_addon/plugin.py, pytest_splunk_addon/standard_lib/event_ingestors/hec_event_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/hec_metric_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/hec_raw_ingestor.py, pytest_splunk_addon/standard_lib/event_ingestors/ingestor_helper.py, pytest_splunk_addon/standard_lib/event_ingestors/sc4s_event_ingestor.py, pytest_splunk_addon/standard_lib/index_tests/test_generator.py, pytest_splunk_addon/standard_lib/index_tests/test_templates.py, pytest_splunk_addon/standard_lib/sample_generation/eventgen_parser.py, pytest_splunk_addon/standard_lib/sample_generation/rule.py, pytest_splunk_addon/standard_lib/sample_generation/sample_event.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py, pytest_splunk_addon/standard_lib/sample_generation/time_parser.py, pytest_splunk_addon/standard_lib/utilities/create_new_eventgen.py
- Added Log messages to give more information to developers, and help debug issues that may occur while running pytest-splunk-addon
- Have also changed the log level for the addon so that only INFO level messages are logged.
=> Adding log messages

pytest_splunk_addon/standard_lib/event_ingestors/sc4s_event_ingestor.py
SC4S default max connections is 2k this change removes threading as the performance gains are low
=> [fix] when threading syslog we can run out of connections

pytest_splunk_addon/splunk.py
Fixed the splunk_rest_uri fixture in splunk.py
=> Fixed the splunk_rest_uri fixture in splunk.py

pytest_splunk_addon/splunk.py
=> fix-minor-stuff

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
- Updated validity of icmp_type field in All_Traffic data model
=> ACD-4555: Updated validity of icmp_type field in All_Traffic data model

pytest_splunk_addon/standard_lib/addon_parser/transforms_parser.py
Summary:
- Updated regex after which PSA generates missing tests.
- Before Regex updates: https://regex101.com/r/Zw3sN6/4
- After Regex updates: https://regex101.com/r/Zw3sN6/3
=> Bugfix/ACD-4557 fixed the transforms-regex

pytest_splunk_addon/standard_lib/data_models/Web.json
Updated the fields cookie, http_referrer, and site within the Web Datamodel to be allowed
=> Updating requirements inside of web DM 

poetry.lock, pyproject.toml
Summary:
- Added pytest-ordering requirement in poetry.
=> Fix/Add pytest-ordering

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
Updated the fields dest_zone and src_zone within network Traffic to the new requirements
=> Updating src_zone and dest_zone within Network Traffic DM

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
Updated the fields src_translated_ip and dest_translated_ip in network traffic to meet the new requirements.
=> Updating src_translated_ip and dest_translated_ip within Network Traffic DM

pytest_splunk_addon/standard_lib/cim_tests/field_test_helper.py, pytest_splunk_addon/standard_lib/cim_tests/test_templates.py
Fixed the issue of the whole query not getting recorded for CIM required fields tests
=> ACD-4536 Whole Query in CIM Required Fields

pytest_splunk_addon/standard_lib/data_models/Network_Traffic.json
As a part of this PR, the following has been completed:
- Updated the fields dest_mac, dest_ip, src_ip and src_mac of Network-Traffic.
Jira Link: https://jira.splunk.com/browse/ACD-4532
=> ACD-4532: Updating field type in Network Traffic data model

pytest_splunk_addon/helmut/__init__.py, pytest_splunk_addon/helmut/log/__init__.py
Added support to store log of helmut.
=> ACD-4560 Add logging in helmut

docs/cim_tests.rst
- Minor Update in doc for CIM compliance
=> test: minor update in doc

.github/workflows/test_matrix.yml, tests/unit/conftest.py, tests/unit/test_eventtype_parser.py, tests/unit/test_tags_parser.py
ut for tags_parser.py + eventtype_parser ut refactor
=> Feature/unit tests/tags parser

.github/workflows/black-style-check.yml, poetry.lock, pyproject.toml, tests/__init__.py, tests/unit/conftest.py, tests/unit/test_example.py, tests/unit/test_props_parser.py
Unit tests for props_parser module
=> Feature/unit tests/infra 30036/props parser

tests/unit/conftest.py, tests/unit/test_fields.py, tests/unit/test_props_parser.py, tests/unit/test_pytest_addon_init.py
Unit tests for field.py and __init__.py from addon_parer
JIRA: INFRA-30109
=> Feature/unit tests/infra 30109/fields

tests/unit/test_tags_parser.py, tests/unit/test_transforms_parser.py
Unit tests for transforms_parser from addon_parer
JIRA: INFRA-30097
=> Feature/unit tests/infra 30097/transforms parser

.circleci/config.yml, docs/how_to_use.rst, pytest_splunk_addon/splunk.py, pytest_splunk_addon/standard_lib/event_ingestors/file_monitor_ingestor.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py, tests/constants.py
- Creating a directory with hostname and a sample file inside that directory with the name of source.
- Added host_segment key in inputs.conf to identify host for the event.
=> Updated file creation mechanism in file monitor

poetry.lock, pyproject.toml
use junitparser library in version below 2.0.0
=> junitparser below <2.0.0

tests/unit/tests_standard_lib/test_fields_tests/test_field_bank.py, tests/unit/tests_standard_lib/test_fields_tests/test_test_generator.py
unit tests for standard_lib/fields_tests
=> Feature/unit tests/infra 30040/fields tests

tests/unit/tests_standard_lib/conftest.py, tests/unit/tests_standard_lib/test_cim_compliance/test_cim_report_generator.py, tests/unit/tests_standard_lib/test_cim_compliance/test_markdown_report.py, tests/unit/tests_standard_lib/test_cim_compliance/test_markdown_table.py, tests/unit/tests_standard_lib/test_cim_compliance/test_plugin.py
unit tests for standard_lib/cim_compliance
=> Feature/unit tests/infra 30037/cim compliance

pytest_splunk_addon/standard_lib/data_models/Endpoint.json
JIRA: ACD-4580
Changes were tested under JIRA: https://jira.splunk.com/browse/ADDON-35205
=> Process name  and parent process name validation

.github/workflows/test_matrix.yml, .ignore_splunk_internal_errors, Dockerfile.tests, tests/test_splunk_addon.py
Updated splunk versions[8.0, 8.1, 8.2] in github workflows
Added .ignore_splunk_internal_errors  to ignore errors in _internal
Updated Dockerfile.tests
Updated the submodule for addonfactory_test_matrix_splunk
=> Fixed failing tests for PSA in circleci and github-actions

README.rst
using requirements.txt instead of requirements_dev.txt, as couldnt find the file in repo
=> Updated readme with change directory step

pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py
Combined assertion for DM and field mapping check 
Output for assertion -
``` AssertionError:  Issue with either field extraction or data model.
E         search=search index=* configured username and password |fields * 
E          data model check: True 
E          data model in requirement file  ['Authentication']
E           data model extracted by TA ['Authentication']
E          Field_extraction_check: False 
E          Key value not extracted by TA: {'dest': '127.0.0.1', 'dest_ip': '127.0.0.1'} 
E          Mismatched key value: {'dest': '10.11.12.13', 'dest_ip': '10.11.12.13'}
E          sourcetype of ingested event: cisco:asa 
```
=> assert modified Field check plus DM check

.circleci/config.yml, pytest_splunk_addon/standard_lib/fields_tests/test_templates.py
fix: Adding check to fix issue when search includes savedsearch
=> INFRA-34069 Fix Nested SavedSearch tests

pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py, tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py
Resolve Ingestion failure of Github TA Syslog event - [Ingestion failure](https://github.com/splunk/splunk-add-on-for-github-audit-log-monitoring/runs/4471039458)
=> regex updated rfc3164

pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py, tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py
Add test_name to test string to make it easier to find event in xml by name than by index.
=> feat: add test name in test_string

.github/workflows/build-test-release.yml
=> ci: multiple updates

pytest_splunk_addon/standard_lib/data_models/Alerts.json
Updated expected values for type field as per CIM v5.0.1.
=> chore: updated expected values for type field alert dm

.pre-commit-config.yaml, docs/conf.py, pytest_splunk_addon/helmut/util/searchhelpers.py, pytest_splunk_addon/standard_lib/cim_tests/field_test_adapter.py
This is a noop commit just to trigger a new release.
=> fix: pre-commit autoupdate

pytest_splunk_addon/standard_lib/data_models/DLP.json
fix: correct search constraints for DLP data model
=> fix: correct search constraints for DLP data model

pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py, tests/unit/tests_standard_lib/test_requirement_tests/test_test_generator.py
Fix : https://splunk.atlassian.net/browse/AQA-159
Regex by - https://splunk.atlassian.net/browse/ADDON-50580?focusedCommentId=8984924
=> fix: support date format with year for cisco asa

pytest_splunk_addon/standard_lib/requirement_tests/test_generator.py, pytest_splunk_addon/standard_lib/requirement_tests/test_templates.py, tests/e2e/requirement_test_scripted/sample_requirement_test_scripted.log, tests/e2e/requirement_test_uf/sample_requirement_test_uf.log
Resolve ingestion failure for events with a bounded asterisk.
Event 1
```
<![CDATA[{"Actor": [{"ID": "admin@a830edad9050849NDA3079.onmicrosoft.com", "Type": 5}, {"ID": "10037FFE8EC1E08E", "Type": 3}, {"ID": "Office 365 SharePoint Online", "Type": 1}, {"ID": "00000003-0000-0ff1-ce00-000000000000", "Type": 2}, {"ID": "User_df22f023-9e0f-4d78-bdd5-d496688af11e", "Type": 2}, {"ID": "df22f023-9e0f-4d78-bdd5-d496688af11e", "Type": 2}, {"ID": "User", "Type": 2}], "ActorContextId": "2ed28a74-1f6f-4829-8530-fe359c77d35c", "AzureActiveDirectoryEventType": 1, "CreationTime": "2021-10-26T06:47:20", "ExtendedProperties": [{"Name": "additionalDetails", "Value": "{\"User-Agent\":\"Microsoft ADO.NET Data Services\"}"}, {"Name": "extendedAuditEventCategory", "Value": "Group"}], "Id": …
```
=> fix: restrictive bounded asterisk issue

pyproject.toml, pytest_splunk_addon/standard_lib/index_tests/test_templates.py, pytest_splunk_addon/standard_lib/sample_generation/sample_stanza.py
it's decided to do not tokenize samples, below alignment allows to use static host
=> fix: skip tokenization

README.rst
=> fix: actually make a release

README.rst
Added steps on how to run e2e tests locally
=> docs: adding steps to run e2e tests locally

.github/workflows/docs.yml
We can allow to live without strict mode for now.
=> ci(docs): no strict mode

poetry.lock, pyproject.toml
=> chore(deps): updating dependencies

pytest_splunk_addon/sample_generation/schema.xsd, tests/unit/tests_standard_lib/tests_sample_generation/test_data/xmls/lr_incorrect.xml, tests/unit/tests_standard_lib/tests_sample_generation/test_data/xmls/lr_notes.xml, tests/unit/tests_standard_lib/tests_sample_generation/test_data/xmls/lr_without_notes.xml, tests/unit/tests_standard_lib/tests_sample_generation/test_schema.py
This feature extends LR schema. Now you can use notes inside `<event>`:
```
<note>some note</note>
```
and field notes:
```
<field name="action" value="created" note="some field level note" />
```
=> feat: schema changes for LR notes

docs/contributing.md
Adding contributing section to the docs
=> docs: adding contributing page

docs/contributing.md, mkdocs.yml
Linking contributing page to mkdocs.yml
=> docs: linking contributing page

pytest_splunk_addon/CIM_Models/datamodel_definition.py, pytest_splunk_addon/data_models/Authentication.json, pytest_splunk_addon/data_models/Endpoint.json, pytest_splunk_addon/data_models/Network_Traffic.json, pytest_splunk_addon/data_models/Updates.json
Adds update to CIM 6.1.0
Diff: https://cd.splunkdev.com/EnterpriseSecurity/sa-commoninformationmodel/-/compare/release%2F6.0.2...release%2F6.1.0
=> feat: support for CIM 6.1.0
